---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dcm4chee
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dcm4chee
    spec:
      initContainers:
      - name: postgreschecker
        image: jonasscherer/service_checker:latest
        env:
          - name: WAIT
            value: "postgres,postgres-keycloak-service.kube-system.svc.cluster.local,5432"
          - name: DELAY
            value: "2"
      containers:
        - name: dcm4chee-container
          image: dcm4che/dcm4chee-arc-psql:5.15.1
          # image: dcm4che/dcm4chee-arc-psql:5.13.3
          # image: dcm4che/dcm4chee-arc-psql:5.13.3-secure
          env:
          - name: LDAP_URL
            value: ldap://ldap-service.kube-system.svc.cluster.local:389
          - name: LDAP_ROOTPASS
            value: secret
          - name: POSTGRES_HOST
            value: postgres-dcm4che-service.default.svc.cluster.local
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: pacsdb
          - name: POSTGRES_USER
            value: pacs
          - name: POSTGRES_PASSWORD
            value: pacs
          - name: HTTP_PORT
            value: "8080"
          - name: HTTPS_PORT
            value: "8443"
          - name: STORAGE_DIR
            value: /storage/fs1
          - name: WILDFLY_CHOWN
            value: /opt/wildfly/standalone /storage
          - name: WILDFLY_WAIT_FOR
            value: ldap-service.kube-system.svc.cluster.local:389 postgres-dcm4che-service.default.svc.cluster.local:5432
          - name: TZ
            value: Europe/Paris
          # - name: GELF_LEVEL
          #   value: INFO
          # - name: AUTH_SERVER_URL
          #   value: https://192.168.99.102:8080/auth
          # - name: REALM_NAME
          #   value: jipdktk
          # - name: UI_CLIENT_ID
          #   value: jip
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 9990
            - containerPort: 11112
            - containerPort: 2575
          volumeMounts:
            - mountPath: /opt/wildfly/standalone
              name: standalone-data
            - mountPath: /storage
              name: storage-data
      volumes:
        - name: standalone-data
          hostPath:
            path: /data_deployment/dcm4che/server_data
            type: DirectoryOrCreate
        - name: storage-data
          hostPath:
            path: /data_deployment/dcm4che/dicom_data
            type: DirectoryOrCreate
---
